//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComandaIteme
    {
        public long ComandaItemID { get; set; }
        public Nullable<long> ComandaID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Cantitate { get; set; }
    
        public virtual Comanda Comanda { get; set; }
        public virtual Item Item { get; set; }
    }
}
