//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiItem
    {
        public int ItemID { get; set; }
        public string CodBare { get; set; }
        public string Producator { get; set; }
        public Nullable<System.DateTime> DataExp { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
